# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jouba"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gregory"]
  s.date = "2014-06-03"
  s.description = "TODO: longer description of your gem"
  s.email = "greg2502@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/jouba.rb",
    "lib/jouba/aggregate_root.rb",
    "lib/jouba/data/event.rb",
    "lib/jouba/data/snapshot.rb",
    "lib/jouba/entity.rb",
    "lib/jouba/event.rb",
    "lib/jouba/exceptions.rb",
    "lib/jouba/extensions/data/mongoid/event.rb",
    "lib/jouba/extensions/data/mongoid/snapshot.rb",
    "lib/jouba/extensions/data/service/.gitkeep",
    "lib/jouba/store.rb",
    "lib/jouba/version.rb",
    "spec/jouba_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/gregory/jouba"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<wisper>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 2.0.5"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.18"])
      s.add_runtime_dependency(%q<wisper>, ["~> 1.3.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<reek>, ["~> 1.2.8"])
    else
      s.add_dependency(%q<wisper>, ["~> 1.3.0"])
      s.add_dependency(%q<hashie>, ["~> 2.0.5"])
      s.add_dependency(%q<activesupport>, ["~> 3.2.18"])
      s.add_dependency(%q<wisper>, ["~> 1.3.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<reek>, ["~> 1.2.8"])
    end
  else
    s.add_dependency(%q<wisper>, ["~> 1.3.0"])
    s.add_dependency(%q<hashie>, ["~> 2.0.5"])
    s.add_dependency(%q<activesupport>, ["~> 3.2.18"])
    s.add_dependency(%q<wisper>, ["~> 1.3.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<reek>, ["~> 1.2.8"])
  end
end

